# Generated by Django 6.1.2 on 2026-10-10 08:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200)),
                ("student_number", models.CharField(blank=True, max_length=32)),
                ("student_name", models.CharField(blank=True, max_length=200)),
                ("staff_role", models.CharField(blank=True, max_length=50)),
                ("staff_name", models.CharField(blank=True, max_length=200)),
                ("last_message", models.TextField(blank=True)),
                ("last_message_time", models.DateTimeField(blank=True, null=True)),
                ("unread_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "staff_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff_rooms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_rooms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(blank=True)),
                ("message_type", models.CharField(default="text", max_length=20)),
                (
                    "image_file",
                    models.ImageField(blank=True, null=True, upload_to="chat/images/"),
                ),
                (
                    "audio_file",
                    models.FileField(blank=True, null=True, upload_to="chat/audio/"),
                ),
                (
                    "video_file",
                    models.FileField(blank=True, null=True, upload_to="chat/video/"),
                ),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="chat/files/"),
                ),
                ("file_name", models.CharField(blank=True, max_length=255)),
                ("file_size", models.IntegerField(blank=True, null=True)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sender",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chat.chatroom",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
