# Generated by Django 6.1.2 on 2026-10-10 08:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClearanceForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("id_number", models.CharField(db_index=True, max_length=32)),
                ("student_email", models.EmailField(blank=True, max_length=254)),
                ("college", models.CharField(blank=True, max_length=200)),
                ("department_name", models.CharField(blank=True, max_length=200)),
                ("program_level", models.CharField(blank=True, max_length=100)),
                ("enrollment_type", models.CharField(blank=True, max_length=100)),
                ("year", models.CharField(blank=True, max_length=50)),
                ("semester", models.CharField(blank=True, max_length=50)),
                ("reason", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_department", "Pending Department"),
                            ("approved_department", "Approved Department"),
                            ("approved_library", "Approved Library"),
                            ("approved_cafeteria", "Approved Cafeteria"),
                            ("approved_psychology", "Approved Psychology"),
                            ("approved_sportmaster", "Approved Sportmaster"),
                            ("approved_campuspolice", "Approved Campuspolice"),
                            ("approved_cooperationsharing", "Approved Cooperation"),
                            ("approved_dopcordinator", "Approved Dop"),
                            ("approved_studentaffairs", "Approved Studentaffairs"),
                            ("approved_dormitory", "Approved Dormitory"),
                            ("Cleared by Registrar", "Cleared By Registrar"),
                            ("rejected", "Rejected"),
                            ("requires_library_payment", "Requires Library Payment"),
                            (
                                "requires_cafeteria_payment",
                                "Requires Cafeteria Payment",
                            ),
                            (
                                "requires_dormitory_payment",
                                "Requires Dormitory Payment",
                            ),
                            ("pending_resubmission", "Pending Resubmission"),
                        ],
                        default="pending_department",
                        max_length=40,
                    ),
                ),
                ("can_resubmit", models.BooleanField(default=False)),
                ("note", models.TextField(blank=True)),
                ("department_note", models.TextField(blank=True)),
                (
                    "department_approved_by",
                    models.CharField(blank=True, max_length=200),
                ),
                ("library_note", models.TextField(blank=True)),
                ("library_approved_by", models.CharField(blank=True, max_length=200)),
                ("cafeteria_note", models.TextField(blank=True)),
                ("cafeteria_approved_by", models.CharField(blank=True, max_length=200)),
                ("psychology_note", models.TextField(blank=True)),
                (
                    "psychology_approved_by",
                    models.CharField(blank=True, max_length=200),
                ),
                ("sportmaster_note", models.TextField(blank=True)),
                (
                    "sportmaster_approved_by",
                    models.CharField(blank=True, max_length=200),
                ),
                ("campuspolice_note", models.TextField(blank=True)),
                (
                    "campuspolice_approved_by",
                    models.CharField(blank=True, max_length=200),
                ),
                ("cooperationsharing_note", models.TextField(blank=True)),
                (
                    "cooperationsharing_approved_by",
                    models.CharField(blank=True, max_length=200),
                ),
                ("dopcordinator_note", models.TextField(blank=True)),
                (
                    "dopcoordinator_approved_by",
                    models.CharField(blank=True, max_length=200),
                ),
                ("studentaffairs_note", models.TextField(blank=True)),
                (
                    "studentaffairs_approved_by",
                    models.CharField(blank=True, max_length=200),
                ),
                ("dormitory_note", models.TextField(blank=True)),
                ("dormitory_approved_by", models.CharField(blank=True, max_length=200)),
                ("registrar_note", models.TextField(blank=True)),
                ("registrar_approved_by", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "building",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.building",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clearance_forms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
